services:
  db:
    image: postgres:16
    environment:
      POSTGRES_DB: taskmanager
      POSTGRES_USER: taskuser
      POSTGRES_PASSWORD: taskpassword
    ports:
      - "5433:5432" # Using port 5433 instead of 5432 as 5432 is already being used by a native Postgres install on my machine
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
